server:
  port: 8090

spring:
  datasource:
#    url: jdbc:mysql://43.154.64.188:3306/jobexploration?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    url: jdbc:mysql://82.156.137.114:3306/jobexploration?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: job
    password: job@502

Logging:
  level:
    com.wms: debug